- block_writer/main.go
The Block Writer example program is designed to write random blocks of data to a
single table in CockroachDB.  Writes are spread randomly across the table's
primary key via a randomized ID, and are never read.
The intention of this program is to create a large amount of data in CockroachDB
quickly, in order to quickly generate split and rebalance events.
> Move block_writer example from main Cockroach repo

- filesystem/block.go
- filesystem/block_test.go
- filesystem/fs.go
- filesystem/main.go
- filesystem/main_test.go
- filesystem/node.go
- filesystem/sql.go
This all got a lot more complicated, but also a lot more efficient.
It'll get better still if we make some of the builtins work with bytes
(eg: `LEFT`, `RIGHT`, `RPAD`, `CONCAT`).
Also reworked the inode structure a bit. It'll make it easier to support
symlinks.
> Store data in a 'block' table.

- Makefile
- build/build-examples.sh
- build/builder.sh
- build/circle-test.sh
- build/push-aws.sh
- circle.yml
Performs the following:
* go get dependencies
* run all tests (only in filesystem/ for now, investigating flakiness)
* build static block_writer example
* push block_writer binary to AWS
This is much dumber than the cockroachdb logic. Among others:
* dependencies are only fetched through go get
* make check cannot run on circle-ci due to missing commands
I do prefer keeping the dependencies more dynamic, since examples are
the kinds of things that should work out of the box.
> Circle-ci config for examples-go repo.

- Makefile
- block_writer/README.md
- block_writer/main.go
- fakerealtime/README.md
- fakerealtime/main.go
A running cockroach node or cluster is required.
Added readme with instructions on how to run it against:
* single dev node
* insecure node or cluster
* secure node or cluster
My plan is to do this for all examples. Specifically:
* no more dependency on cockroach/server (makes binaries and compile
times huge)
* identical flags (`--db-url`, although I may change this)
* readme with short description and usage
> Remove testserver from block_writer.

- filesystem/fs.go
This is needed because of the change in https://github.com/cockroachdb/cockroach/pull/3990.
> Replace experimental_unique_int() with unique_rowid()

- block_writer/main.go
It now looks like:
1s: 3028.0/sec
2s: 2929.2/sec
3s: 2742.2/sec
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/41)
> block_writer: simplify status output

- photos/db.go
See https://github.com/cockroachdb/cockroach/issues/4925#issuecomment-196513251
> Use more efficient query

- bank/main.go
- block_writer/main.go
- fakerealtime/main.go
- filesystem/main.go
- photos/db.go
Technically, only the filesystem example needs it since the tests import
the testserver, causing double registration of the postgres driver.
However, better be consistent and avoid a surprise for anyone adding
tests to the other examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/48)
> Switch to cockroachdb/pq driver.

- Makefile
- build/build-examples.sh
- circle.yml
* local go install (the netgo suffix causes permission denied)
* don't check for "statically linked", they aren't.
* also strip photos binary
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/52)
> make static builds work again without docker

- block_writer/main.go
The previous default of 3 was insufficient to drive sustained load.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/69)
> Default --concurrency to 2*runtime.NumCPU()

- block_writer/main.go
Avoid closing idle connections immediately by setting max idle conns to
the same value as max open conns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/70)
> block_writer: set max idle conns

- photos/main.go
- photos/user.go
Upon termination, `photos` now outputs Go benchmark stats. The benchmark
name must be passed in through the new `--benchmark-name` flag, because
only the continuous load tester framework knows the intended duration of
the test (which should be included in the benchmark name).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/74)
> photos: add benchmark output to photos

- photos/db.go
- photos/user.go
- photos/user_test.go
Comments for the empty photo ID will have very high contention,
eventually bringing the process to a standstill.
Explicitly check for this case, and add a CHECK constraint to the schema
to ensure that any empty UUIDs that make it through to the database will
be rejected.
Updates cockroachdb/cockroach#9247
@cockroachdb/stability
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/78)
> photos: Avoid inserting comments with empty photo IDs 

- block_writer/main.go
- photos/main.go
- photos/user.go
The value of this flag controls how many blocks to insert with each SQL
statement. This feature is meant to help stress the parallelizing dist
sender.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/81)
> Add -batch command line flag to block_writer

- block_writer/main.go
Output lifetime queries/sec if the duration or max-blocks are limited.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/80)
> block_writer: show lifetime queries/sec

- Makefile
I don't think we need it anymore, and the suffix is making teamcity builds unhappy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/83)
> Stop specifying netgo on static builds

- block_writer/main.go
Previously block_writer was exiting when any signal was received. For
example, if the remote node it was talking to terminated abruptly
block_writer could receive a SIGPIPE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/86)
> block_writer: only exit on SIGINT and SIGTERM

- block_writer/main.go
Latency is measured over the reporting interval (1s).
```
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
1s        0         5689.5         5689.4      2.5      4.7      5.8     10.5
2s        0         4903.8         5297.8      2.9      6.0      7.6     16.8
3s        0         5297.6         5297.7      2.6      6.0      8.4     16.8
4s        0         4776.6         5167.5      2.9      7.1     10.0     13.6
5s        0         4759.7         5086.1      2.9      7.3     11.0     14.2
6s        0         4945.3         5062.7      2.8      6.6     10.5     14.2
7s        0         4768.4         5020.8      2.8      7.1     14.2     22.0
8s        0         4914.9         5007.5      2.8      6.8     12.1     18.9
9s        0         4258.1 …
```
> block_writer: add p{50,95,99,max} latency stats

- block_writer/main.go
`CREATE DATABASE IF NOT EXISTS` fails is we're not root.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/98)
> Add --create-db flag to block_writer.

- ledger/README.md
- ledger/main.go
Allow specifying number of source and number of destination accounts. This
simplifies the previous flag `--generator`:
- `--generator many-many` is now `--sources 0 --destinations 0`
- `--generator few-few` is now `--sources 10 --destinations 10`
- `--generator few-one` is now `--sources 10 --destinations 1`
etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/100)
> ledger: more flexible generators

- photos/db.go
- photos/main.go
- photos/user.go
Add analytics queries, which are optionally run with the
'--analytics-true' flag. This is default false to provide minimal
disruption to existing benchmarks, since it will cause throughput
numbers to decrease.
The analytics queries are specifically designed to trigger full table
scans and exercise various parts of the DistSQL code paths.
> photos: add analytics queries to photos

- photos/db.go
- photos/user.go
Currently, `photos` issues about 0.1 DistSQL queries per second on my
laptop.
With these new queries, `photos` issues ~70 qps through DistSQL on my
laptop, which is about 12% of total reads. The new queries filter on an
indexed column then sort on a non-indexed column. The sorting part
triggers DistSQL.
> photos: add more OLTP queries that use DistSQL

- bank2/main.go
Previously, cases `fromBalance < amount` would count as a success but
would not count towards the aggregate measurements. This skewed the
measurements significantly so that it looked like transactions were much
faster than they actually were.
> bank2: correctly increment successCount

- bank2/main.go
allows performance of comparison of two DML methods (update vs upsert) to achieve the same result.  multi-row capability of upsert should make upsert faster.  This is an initial PR to add update vs upsert 
graph of 4 iterations 
./bank2 --contention high postgres://root@localhost:26257?sslmode=disable
./bank2 --updatemethod upsert --contention high postgres://root@localhost:26257?sslmode=disable
./bank2 --contention high postgres://root@localhost:26257?sslmode=disable
./bank2 --updatemethod upsert --contention high postgres://root@localhost:26257?sslmode=disable
> add option to use upsert instead of update
