fakerealtime/.gitignore, fakerealtime/main.go
Moved from cockroachdb/cockroach#2627.
=> Add fakerealtime example.

Makefile
The end goal is to build these on circleci, or using docker builder
image.
=> Add build rules for examples.

block_writer/main.go
should be useful for https://github.com/cockroachdb/cockroach/issues/3087 and in general.
=> continue running despite errors

Makefile, bank/sql_bank/.gitignore, bank/sql_bank/README.md, bank/sql_bank/main.go, block_writer/README.md, block_writer/main.go, fakerealtime/main.go, filesystem/README.md, filesystem/fs.go, filesystem/main.go, filesystem/node.go
* minimize dependencies on cockroach repo. sql driver only
* add README for all examples
* use `--db-url` flag everywhere with same meaning
=> Simplify and document examples.

block_writer/main.go
this allows running multiple block_writers
in parallel without interference.
changed --tolerate-errors semantics: writer
retries indefinitely during initialization.
Fixes #26.
=> don't drop blocks table

filesystem/README.md, filesystem/block_test.go, filesystem/fs.go, filesystem/main.go
The only change is splitting multi-statement execs into individual ones.
Manual testing shows it works. I still need to add proper fs-level
testing.
=> Switch to pq driver for filesystem examples.

block_writer/main.go
Fixes cockroachdb/cockroach#4420
=> Blockwriter: use new UUID

filesystem/node.go
=> Fix FS vet errors

.gitignore, photos/db.go, photos/main.go, photos/user.go
Fixes cockroachdb/cockroach#3976
=> Implementation of persistent load generator.

fakerealtime/README.md, fakerealtime/main.go
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/40)
=> fakerealtime: move to pgwire driver

bank/sql_bank/README.md, bank/sql_bank/main.go
Currently panics the server (see https://github.com/cockroachdb/cockroach/issues/4691), so might want to want until that bug is fixed before landing this.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/39)
=> bank_sql: switch to pgwire only

.gitignore, photos/db.go, photos/main.go
- Update DB URL to port 26257 and specify the database name
- Don't use `photos.` prefix in SQL code (assume database was specified in conn params)
- Make use of efficient limit queries for finding an existing user id (and use order by)
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/42)
=> Update photos app

photos/main.go, photos/user.go
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/43)
=> Split stats computation into a new worker

build/push-aws.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/44)
=> Setup static hosting redirect to real binary

Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/51)
=> Remove installsuffix flag, it looks like it's not longer necessary.

filesystem/block_test.go
Depends on https://github.com/cockroachdb/cockroach-go/pull/2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/53)
=> Update testserver usage

build/build-examples.sh, build/push-aws.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/54)
=> Build and push all examples. I plan on using some of them.

build/push-aws.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/55)
=> TBR: fix typo

photos/db.go, photos/user.go
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/56)
=> Update photos example app to use the new txn wrapper

photos/user.go
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/58)
=> Move from cdb to crdb

filesystem/block_test.go, filesystem/fs.go, filesystem/node.go
Also change test to use the short invocation of the testserver
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/57)
=> Retry transactions in filesystem test.

photos/db.go
The commentsByPhotoID index was not actually unique as multiple comments
with the same timestamp could be inserted by the load-generator. Easy to
reproduce by running `photos --users 100`. Completely removed this index
and changed the primary key of the comments table to include the
timestamp which allowed a slight simplification of the query on the
comments table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/59)
=> Adjust indexing for photos.comments table.

block_writer/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/61)
=> Default the block_writer url to localhost, insecure cockroach.

photos/db.go
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/60)
=> Use uuid_v4() instead of experimental_uuid_v4().

filesystem/README.md
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/37)
=> Replace mention of --dev with --insecure.

photos/db.go, photos/user.go
photos wasn't fixed to use pkg/errors when the cockroach repo was.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/67)
=> Fix build issues for photos

block_writer/main.go
These flags can limit how long `block_writer` runs allowing it to be
used for fixed duration performance tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/68)
=> Add --max-blocks and --duration flags

block_writer/main.go
When block_writer terminates (usually through `-max-blocks` or
`-duration` being specified), we now output performance in the Go
benchmark style. For example:
```
BenchmarkBlockWriter	  104320	    191734.5 ns/op
```
Partly addresses cockroachdb/cockroach#7580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/72)
=> block_writer: add Go benchmark output

ledger/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/76)
=> ledger: don't require a URL with a path in it

bank/main.go, block_writer/main.go, fakerealtime/main.go, filesystem/main.go, ledger/main.go, photos/db.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/75)
=> Stop using cockroach's forked lib/pq.

block_writer/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/79)
=> add a Dockerfile for block_writer

filesystem/block_test.go, filesystem/main_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/82)
=> Fix bad imports in examples-go

bank2/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/85)
=> Address PR comments, added retry count

block_writer/main.go
Add a flag to pre-split the datablocks.blocks table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/88)
=> block_writer: add -splits flag

photos/main.go
splits all three tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/90)
=> Add split command to photos example

Makefile, hotspot/.gitignore, hotspot/README.md, hotspot/main.go
This new example is designed to make a single row an extreme hotspot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/91)
=> hotspot: add a new example load

photos/user.go
Hash user IDs after generation to avoid having a single range contain
all of the "hot" users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/92)
=> photos: improve user ID generation

block_writer/main.go
Fixes #94
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/95)
=> block_writer: avoid negative elapsed times

block_writer/main.go
Fixes #94
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/96)
=> block_writer: clamp latency to both a min and max value

ledger/README.md, ledger/main.go
I'm not sure why `SetMaxOpenConns` is important. Anyone wanna shed light on that?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/66)
=> Brush up ledger example

block_writer/main.go, photos/main.go
See https://github.com/cockroachdb/cockroach/pull/14281.
Not sure when this should go in - perhaps when the first beta with incorporates the PR above is released?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/102)
=> updating uses of SPLIT AT

Makefile, bank2/main.go
Using the new syntax introduced in https://github.com/cockroachdb/cockroach/pull/14188.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/103)
=> Add --parallel-stmts flag to bank2

teamcity-push.sh, teamcity-test.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/examples-go/108)
=> Avoid `go get` in Docker  creating root-owned files

block_writer/Dockerfile
for example: https://github.com/lib/pq/issues/741
=> some of the dependencies require a newer go version
